apiVersion: skaffold/v4beta13
kind: Config

deploy:
  kubectl: {}

manifests:
  rawYaml:
    - ./infra/k8s/*

build:
  local:
    push: false
  artifacts:
    - image: faheem222/user
      context: ./user
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.ts"
            dest: .
