export const AppErrorCodes = {
  // App errors
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",

  // Infra errors
  INFRA_UNAVAILABLE: "INFRA_UNAVAILABLE",

  // ES errors
  ES_CONNECTION_ERROR: "ES_CONNECTION_ERROR",
  ES_QUERY_ERROR: "ES_QUERY_ERROR",
  ES_TIMEOUT_ERROR: "ES_TIMEOUT_ERROR",
  ES_INDEX_NOT_FOUND: "ES_INDEX_NOT_FOUND",
  ES_MAPPING_ERROR: "ES_MAPPING_ERROR",
} as const;

export type AppErrorCodes = keyof typeof AppErrorCodes;
