apiVersion: v1
kind: Namespace
metadata:
  name: elasticsearch
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-pvc
  namespace: elasticsearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-depl
  namespace: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: es-depl
  template:
    metadata:
      labels:
        app: es-depl
    spec:
      containers:
        - name: es
          image: docker.elastic.co/elasticsearch/elasticsearch:9.1.3
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "750m"
          ports:
            - containerPort: 9200
          env:
            - name: discovery.type
              value: single-node
            - name: ES_JAVA_OPTS
              value: "-Xms128m -Xmx512m"
            - name: xpack.security.enabled # turning off https for dev env
              value: "false"
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: es-storage
      volumes:
        - name: es-storage
          persistentVolumeClaim:
            claimName: es-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: es-srv
  namespace: elasticsearch
spec:
  selector:
    app: es-depl
  ports:
    - name: rest
      protocol: TCP
      port: 9200
      targetPort: 9200
