export const DomainErrorCodes = {
  NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  BLOCKED_USER: "BLOCKED_USER",
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VERIFIED_USER: "VERIFIED_USER",
  ALREADY_EXISTS: "ALREADY_EXISTS",
  AUTH_PROVIDER_CONFLICT: "AUTH_PROVIDER_CONFLICT",
  SELF_CONNECTION_ERROR: "SELF_CONNECTION_ERROR",
  REJECTING_ACCEPTED_CONNECTION_ERROR: "REJECTING_ACCEPTED_CONNECTION_ERROR",
  CONFLICTING_CONNECTION_REQUEST_ERROR: "CONFLICTING_CONNECTION_REQUEST_ERROR",
  NOT_VERIFIED_ERROR: "NOT_VERIFIED_ERROR",
} as const;

export type DomainErrorCodes = keyof typeof DomainErrorCodes;
