export const DomainErrorCodes = {
  NOT_FOUND_ERROR: "NOT_FOUND_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  BLOCKED_USER: "BLOCKED_USER",
  UNAUTHORIZED: "UNAUTHORIZED",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  VERIFIED_USER: "VERIFIED_USER",
} as const;

export type DomainErrorCodes = keyof typeof DomainErrorCodes;
