apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
    spec:
      initContainers:
        - name: wait-for-dependencies
          image: busybox
          command:
            [
              "sh",
              "-c",
              "timeout 60 sh -c 'until nc -z user-pg-srv 5432; do echo waiting for db; sleep 2; done && until nc -z my-rabbit 5672; do echo waiting for rabbitmq; sleep 2; done'",
            ]
      containers:
        - name: user
          image: faheem222/user
          envFrom:
            - configMapRef:
                name: user-config
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: my-rabbit-default-user # created by operator
                  key: username
            - name: RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-rabbit-default-user # created by operator
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: user-srv
spec:
  selector:
    app: user
  ports:
    - name: user
      protocol: TCP
      port: 3000
      targetPort: 3000
