apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-pg-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-pg
  template:
    metadata:
      labels:
        app: user-pg
    spec:
      containers:
        - name: user-pg
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: user-pg-srv
spec:
  selector:
    app: user-pg
  ports:
    - name: db
      protocol: TCP
      port: 5432
      targetPort: 5432
